# Generated by Django 5.2.6 on 2025-10-27 00:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['due_date', '-created_at'], 'verbose_name': 'Todo', 'verbose_name_plural': 'Todos'},
        ),
        migrations.RemoveField(
            model_name='todo',
            name='complete',
        ),
        migrations.AddField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('skipped', 'Skipped')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='todo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
